twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        company_email: '%env(resolve:COMPANY_EMAIL)%'
        address:
            name: '%env(resolve:COMPANY_ADDRESS)%'
            map_link: '%env(resolve:COMPANY_MAP_LINK)%'
        social_network:
            facebook: '%env(resolve:FACEBOOK)%'
            instagram: '%env(resolve:INSTAGRAM)%'
when@test:
    twig:
        strict_variables: true
